version: 1.0.{build}
build_cloud: allan-VirtualBox
image: Linux
build:
  verbosity: normal
init:
- sh: npm install vsce
install:
- sh: npm install
build_script:
- sh: >-
    npm run compile

    npx vsce package

    uname -a >> platform.txt

    sw_vers >> platform.txt
artifacts:
- path: '*.vsix'
- path: platform.txt

